# Site/SEO settings
email: hello@jessicaarmstrong.io
baseurl: ""
permalink: /:year/:month/:day/:title/
google_analytics:

name: Jessica Armstrong
title: Jessica Armstrong
description: >
  Consultant and agilist extraordinaire.
url: http://jessicaarmstrong.io
twitter_username: j_armstrng
default_img: /assets/images/seo.jpg
social:
  - name: twitter
    url: https://twitter.com/j_armstrng
  - name: linkedin
    url: https://www.linkedin.com/in/jarmstrng/

# Contact settings
contact_img: /assets/images/placeholder-28.jpg
formcarry: https://formcarry.com/s/oGNo-4hJrWM

# Disqus settings
disqus:

# MailChimp settings
mailchimp_action: https://jessicaarmstrong.us4.list-manage.com/subscribe/post?u=b502b7e4cc5041e4c1086609c&amp;id=52fa5cfb76
mailchimp_input: b_b502b7e4cc5041e4c1086609c_52fa5cfb76

# Author settings
author:
  - name: Jessica Armstrong
    bio: Jessica has lived in seven US states and traveled to 19 countries, but is happy to call Brooklyn "home".
    url: http://jessicaarmstrong.io

# Pagination settings
pagination:
  enabled: true
  debug: false
  per_page: 12
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts:
      - 'tag.html'
    title: 'Jessica Armstrong'
    permalink: '/tag/:tag'
    slugify:
      mode: raw
      cased: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
  - vendor
