AWSTemplateFormatVersion: '2010-09-09'
Description: Website stack

Parameters:

  DomainName:
    Type: String
    Default: "jessicaarmstrong.io"

  HostedZoneName:
    Type: String
    Default: "jessicaarmstrong.io."

  HostedZoneId:
    Type: String
    Default: "Z3T2AYXN75BAG8"

  RefererSecret:
    Type: String
    NoEcho: true


Resources:

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
        - NoncurrentVersionExpirationInDays: 30
          Status: Enabled

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject
            Principal: '*'
            Effect: Allow
            Resource: !Sub "${Bucket.Arn}/*"
            Condition:
              StringLike:
                "aws:Referer": [ !Ref RefererSecret ]

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Aliases:
          - !Ref DomainName
          - !Join ['.', ['www', !Ref DomainName]]
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          ViewerProtocolPolicy: redirect-to-https
          TargetOriginId: S3WebsiteOrigin
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          Compress: true
        PriceClass: PriceClass_100
        Origins:
          - Id: S3WebsiteOrigin
            DomainName: !Select [1, !Split ['://', !GetAtt Bucket.WebsiteURL]]
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
            OriginCustomHeaders:
              - HeaderName: Referer
                HeaderValue: !Ref RefererSecret
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          SslSupportMethod: sni-only

  RecordSetGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Ref HostedZoneName
      RecordSets:
        - Name: !Ref DomainName
          Type: A
          AliasTarget:
            DNSName: !GetAtt CloudFrontDistribution.DomainName
            HostedZoneId: Z2FDTNDATAQYW2 # Universal CloudFront Hosted Zone ID
        - Name: !Join ['.', ['www', !Ref DomainName]]
          Type: A
          AliasTarget:
            DNSName: !GetAtt CloudFrontDistribution.DomainName
            HostedZoneId: Z2FDTNDATAQYW2

  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames:
        - !Join ['.', ['*', !Ref DomainName]]
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId
